### ISSUE TITLE
Please also capure if the person has taken a shit before weighting as it influences the result

### ISSUE THREAD

**Issue by Tim-is-coding** [Flo-is-coding/dubisoft-weighttracker-frontend#3]
The new JSON for the upload API endpoint is 

{
  "weight": "75kg",
  "takesCreatine": true,
  "**hasTakenAShitBeforeWeighing**": false
}

Please add this data point to future requests. 
To keep the app functional, the backend presets hasTakenAShitBeforeWeighing to "false" as of right now.

**Comment by Flo-is-coding** [comment]
added shit checkbox and adjusted json

**Comment by Tim-is-coding** [comment]
Rejected as key is not as expected.

hasTakenAShitBeforeWeighing was expected but was given tookShit.


<img width="227" alt="grafik" src="https://github.com/user-attachments/assets/e0f54484-2e81-44b5-be8b-a19fae84d343">

**Comment by Flo-is-coding** [comment]
fixed!

**Comment by Tim-is-coding** [comment]
Looks good for now :) Waiting until new data point is captured to reflect changes in the DB

**Comment by Tim-is-coding** [comment]
LGTM!
