### ISSUE TITLE
Display the current streak

### ISSUE THREAD

**Issue by Tim-is-coding** [Flo-is-coding/dubisoft-weighttracker-frontend#4]
Please display it both before and after the weighting. The endpoint uses no cache and is always up to date. 
The user should be incentivized to capture data every day!

The backend returns the current streak using this API Endpoint:
`GET https://dubisoftw-weightracker-backend.azurewebsites.net/api/v1/streak`

The result value is no JSON but just a simple integer value. You can test the api by just visiting the URL using your browser as it is a GET endpoint. [https://dubisoftw-weightracker-backend.azurewebsites.net/api/v1/streak](https://dubisoftw-weightracker-backend.azurewebsites.net/api/v1/streak)

**Comment by Tim-is-coding** [comment]
New enpoint. Response is now e.g:

{"currentStreak":11,"streakActive":true}

**Comment by Flo-is-coding** [comment]
done, please review @Tim-is-coding

**Comment by Tim-is-coding** [comment]
Looks great!
